# IT IS A TYPE OF COLLECTION
# IT IS UNORDERED WHICH MEANS IT DOESNOT POSSESS ANY INDEX
# IT IS UNIQUE :- ONE SET DOESNOT REPEATE ITS ELEMENTS..
# THE SETS ARE REPRESENTED WITHIN {}
sets={1,2,3,4,5}
print(sets)
sets.add(6)
print(sets)
